apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
    app: cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
      - name: cloud-gateway
        image: rajureddy98/cloud-gateway:latest
        ports:
          - containerPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-service
  labels:
    app: cloud-gateway-service
spec:
  selector:
    app: cloud-gateway
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
