server:
  port: 9191
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: payment-service
logging:
  file: C:/Users/Basant.Hota/Desktop/oms.log
eureka:
  client:
    service-url:
      defaultZone: http://10.102.205.193:8888/eureka/
